config/routes.rb
Rails.application.routes.draw do

  get 'things' => 'things#new'
  post 'things' => 'things#show'
  get 'test' => 'things#pull_data'
  root to: 'things#new'
end

app/models/thing.rb
class Thing < ActiveRecord::Base

  class << columns_hash['date']
    def type
      :date
    end
  end
  attr_accessor :date, :location

end

app/controllers/things_controller.rb
class ThingsController < ApplicationController




  def new
    @thing = Thing.new

  end

  def create
    @thing = Thing.new(thing_params)
  end

  def save
    @date = params[:date]
    @location = params[:location]

    key= ENV["NASA_KEY"]


    call = HTTParty.get("https://api.nasa.gov/planetary/apod?concept_tags=True&date=#{@date}&api_key=#{key}")

    @url = call["url"]

  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
    @thing = Thing.new(thing_params)

    @date = @thing.date

    @newdate = @date.map{|k,v| "#{v}"}.join('-')







    key= ENV["NASA_KEY"]


    call = HTTParty.get("https://api.nasa.gov/planetary/apod?concept_tags=True&date=#{@newdate}&api_key=#{key}")

    @url = call["url"]
  end

  def pull_data
    key= ENV["NASA_KEY"]


    call = HTTParty.get("https://api.nasa.gov/planetary/apod?concept_tags=True&date=2013-05-01&api_key=#{key}")

    @url = call["url"]

    #call = HTTParty.get("https://en.wikipedia.org/w/api.php?action=query&titles=Main%20Page&prop=revisions&rvprop=content&format=json")

    #@response = call["query"]["pages"]["15580374"]["pageid"]



    #response =
    #    HTTParty.get("http://rubygems.org/api/v1/versions/httparty.json")
    #puts response[0]["number"]
    #@response = response[0]["number"]
  end

  def thing_params
    params.require(:thing).permit(:date, :location)
  end

end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Bootstrap" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container-main">
      <header>
        <%= render 'layouts/navigation' %>
      </header>
         <%= render 'layouts/messages' %>
         <%= yield %>

    </div>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>Simple Nasa API Image Pull</h3>
<p>
This application allows you to view all of NASA's images of the day by selecting a date.
</p>

app/views/things/create.html.erb
<h1>Things#create</h1>
<p>Find me in app/views/things/create.html.erb</p>

app/views/things/destroy.html.erb
<h1>Things#destroy</h1>
<p>Find me in app/views/things/destroy.html.erb</p>

app/views/things/edit.html.erb
<h1>Things#edit</h1>
<p>Find me in app/views/things/edit.html.erb</p>

app/views/things/index.html.erb
<h1>Things#index</h1>
<p>Find me in app/views/things/index.html.erb</p>

app/views/things/new.html.erb
<div class="row front-row">
    <div class="col-md-6 col-md-offset-3">
        <div class="dateselect">
          <h4>Select Date to View Nasa Image of the Day</h4>

          <%= form_for(@thing) do |f|  %>

        <%= f.date_select :date, use_two_digit_numbers: true, start_year: 1996, end_year: 2015, class: 'form-control' %>


        <%= f.submit "Choose Date", class: 'btn btn-success' %>

    <% end %>
      </div>
    </div>
</div>

app/views/things/pull_data.html.erb
    <div style="height: 100px;"></div>

<img src="<%= @url  %>">

app/views/things/save.html.erb
<div style="height: 100px;"></div>

<img src="<%= @url  %>">

app/views/things/show.html.erb
<h3><span><%= @newdate %></span></h3>


<div style="height: 20px;"></div>

<a href="<%= @url %>"><img src="<%= @url  %>"></a>
<div style="height: 15px;"></div>

<button class="btn showbut btn-danger"><%= link_to 'New Image Request', things_path('things') %></button>

<div style="height: 50px;"></div>

<%= debug @url %>
<%= debug @newdate %>

<%= debug @thing.date %>

app/views/things/update.html.erb
<h1>Things#update</h1>
<p>Find me in app/views/things/update.html.erb</p>